config/routes.rb
Rails.application.routes.draw do
  # Rotas para Teams
  get '/teams', to: 'teams#index', as: :teams
  get '/teams/new', to: 'teams#new', as: :new_team
  post '/teams', to: 'teams#create'
  get '/teams/:id', to: 'teams#show', as: :team
  get '/teams/:id/edit', to: 'teams#edit', as: :edit_team
  patch '/teams/:id', to: 'teams#update'
  put '/teams/:id', to: 'teams#update'
  delete '/teams/:id', to: 'teams#destroy'
  patch '/teams/:id/sell_players', to: 'teams#sell_players', as: :sell_players_team
  patch '/teams/:id/buy_players', to: 'teams#buy_players', as: :buy_players_team

  # Rotas para Players
  get '/players', to: 'players#index', as: :players
  get '/teams/:team_id/players', to: 'players#index', as: :team_players
  get '/teams/:team_id/players/new', to: 'players#new', as: :new_team_player
  post '/teams/:team_id/players', to: 'players#create'
  get '/players/:id/edit', to: 'players#edit', as: :edit_player
  patch '/players/:id', to: 'players#update'
  put '/players/:id', to: 'players#update'
  delete '/players/:id', to: 'players#destroy'

  # Rotas para Matches
  get 'matches', to: 'matches#index', as: 'matches_index'
  get 'matches/new', to: 'matches#new', as: 'new_match'
  post 'matches', to: 'matches#create', as: 'matches'
  get 'matches/:id', to: 'matches#show', as: 'match'
  get 'matches/:id/start_match', to: 'matches#start_match', as: 'start_match'
  post 'matches/:id/generate_result', to: 'matches#generate_result', as: 'generate_result_match'

  devise_for :users

  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team, optional: true

  validates :name, uniqueness: true
  validates :name, :position, presence: true
  validates :level, :yellow_card, :red_card, :goal_scored, :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :injury, inclusion: { in: [true, false] }
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user, optional: true
  has_many :players, dependent: :destroy
  has_many :home_matches, class_name: 'Match', foreign_key: 'home_team_id', dependent: :destroy
  has_many :away_matches, class_name: 'Match', foreign_key: 'away_team_id', dependent: :destroy

  validates :name, presence: true
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_team, only: [:new, :create, :index]

  def index
    @players = @team.players
    @other_players = Player.where.not(team_id: @team.id)
  end

  def new
    @team = Team.find(params[:team_id])
    @player = @team.players.build
  end

  def create
    @team = Team.find(params[:team_id])
    @player = @team.players.build(player_params)
    if @player.save
      redirect_to @team, notice: 'Player added successfully.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(player_params)
      redirect_to @player.team, notice: 'Player updated successfully.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to @player.team, notice: 'Player removed successfully.'
  end

  private

  def set_team
    @team = Team.find(params[:team_id])
  end

  def player_params
    params.require(:player).permit(:name, :accuracy, :strength, :speed, :balance, :agility, :price, :position)
  end
end

app/views/players/index.html.erb
<div class="container-players-index">
  <div class="left">
    <%= form_with(model: @team, scope: :sell, url: sell_players_team_path(@team), method: :patch) do |form| %>
      <h3 class="text-center flex-container">
      <%= link_to 'Voltar', team_path(@team), class: 'btn btn-secondary' %>
      <span class="team-cash"><%= number_to_currency(@team.cash) %></span>
      </h3> 
      <div class="scrollable">
        <table>
          <thead>
            <tr>
              <th class="sell-column text-center"></th>
              <th class="name-column text-center">Name</th>
              <th class="position-column text-center">P</th>
              <th class="level-column text-center">Level</th>
              <th class="text-center"> <%= image_tag 'yellow_card.png', class: 'yellow-card-icon' %></th>
              <th class="text-center"> <%= image_tag 'red_card.png', class: 'red-card-icon' %></th>            
              <th class="text-center"><%= image_tag 'goal_ball.png', class: 'goal-ball-icon' %></th>
              <th class="text-center"> <%= image_tag 'cruz-vermelha.png', class: 'injury-icon' %></th>
              <th class="price-column text-center">Price</th>
            </tr>
          </thead>
          <tbody>
            <% @team.players.sort_by { |player| ['G', 'D', 'M', 'A'].index(player.position) || 4 }.each do |player| %>
              <tr>
                <td>
                  <label class="switch">
                    <%= check_box_tag "sell[player_ids][]", player.id, false %>
                    <span class="slider"></span>
                  </label>
                </td>
                <td class="text-center"><%= player.name %></td>
                <td class="text-center"><%= player.position %></td>
                <td class="text-center"><%= player.level %></td>
                <td class="text-center"><%= player.yellow_card %></td>
                <td class="text-center"><%= player.red_card %></td>
                <td class="text-center"><%= player.goal_scored %></td>
                <td class="text-center"><% if player.injury %>
                      <%= image_tag 'cruz-vermelha.png', class: 'injury-icon' %>
                      <% else %>
                      <%= image_tag 'cruz-verde.png', class: 'health-icon' %>
                    <% end %>
                </td>
                <td class="text-center"><%= number_to_currency(player.price, unit: "$", delimiter: ".", precision: 0) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div style="text-align: center;">
        <%= form.submit "Vender Jogadores", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
  <div class="right">
    <%= form_with(model: @team, scope: :buy, url: buy_players_team_path(@team), method: :patch) do |form| %>
      <h2 class="text-center">Jogadores à venda</h2>
      <div class="scrollable">
        <table>
          <thead>
            <tr>
              <th class="sell-column text-center"></th>
              <th class="name-column text-center">Name</th>
              <th class="position-column text-center">P</th>
              <th class="level-column text-center">Level</th>
              <th class="text-center"> <%= image_tag 'yellow_card.png', class: 'yellow-card-icon' %></th>
              <th class="text-center"> <%= image_tag 'red_card.png', class: 'red-card-icon' %></th>            
              <th class="text-center"><%= image_tag 'goal_ball.png', class: 'goal-ball-icon' %></th>
              <th class="text-center"> <%= image_tag 'cruz-vermelha.png', class: 'injury-icon' %></th>
              <th class="price-column text-center">Price</th>
            </tr>
          </thead>
          <tbody>
          <% Player.all.reject { |player| @team.players.include?(player) }.sort_by { |player| -player.position }.each do |player| %>
            <tr>
              <td>
                <label class="switch">
                  <%= check_box_tag "buy[player_ids][]", player.id, false %>
                  <span class="slider"></span>
                </label>
              </td>
              <td class="text-center"><%= player.name %></td>
              <td class="text-center"><%= player.position %></td>
              <td class="text-center"><%= player.level %></td>
              <td class="text-center"><%= player.yellow_card %></td>
              <td class="text-center"><%= player.red_card %></td>
              <td class="text-center"><%= player.goal_scored %></td>
              <td class="text-center">
                <% if player.injury %>
                  <%= image_tag 'cruz-vermelha.png', class: 'injury-icon' %>
                <% else %>
                  <%= image_tag 'cruz-verde.png', class: 'health-icon' %>
                <% end %>
              </td>
              <td class="text-center"><%= number_to_currency(player.price, unit: "$", delimiter: ".", precision: 0) %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <div style="text-align: center;">
      <%= form.submit "Comprar Jogadores", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
  <%= image_tag 'team_show.jpeg', class: 'team-show' %>
</div>