config/routes.rb
Rails.application.routes.draw do
  # Rotas para Teams
  get '/teams', to: 'teams#index', as: :teams
  get '/teams/new', to: 'teams#new', as: :new_team
  post '/teams', to: 'teams#create'
  get '/teams/:id', to: 'teams#show', as: :team
  get '/teams/:id/edit', to: 'teams#edit', as: :edit_team
  patch '/teams/:id', to: 'teams#update'
  put '/teams/:id', to: 'teams#update'
  delete '/teams/:id', to: 'teams#destroy'
  patch '/teams/:id/sell_players', to: 'teams#sell_players', as: :sell_players_team
  patch '/teams/:id/buy_players', to: 'teams#buy_players', as: :buy_players_team

  # Rotas para Players
  get '/players', to: 'players#index', as: :players
  get '/teams/:team_id/players', to: 'players#index', as: :team_players
  get '/teams/:team_id/players/new', to: 'players#new', as: :new_team_player
  post '/teams/:team_id/players', to: 'players#create'
  get '/players/:id/edit', to: 'players#edit', as: :edit_player
  patch '/players/:id', to: 'players#update'
  put '/players/:id', to: 'players#update'
  delete '/players/:id', to: 'players#destroy'

  # Rotas para Matches
  get 'matches', to: 'matches#index', as: 'matches_index'
  get 'matches/new', to: 'matches#new', as: 'new_match'
  post 'matches', to: 'matches#create', as: 'matches'
  get 'matches/:id', to: 'matches#show', as: 'match'
  get 'matches/:id/start_match', to: 'matches#start_match', as: 'start_match'
  post 'matches/:id/generate_result', to: 'matches#generate_result', as: 'generate_result_match'

  devise_for :users

  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :home_team, class_name: 'Team'
  belongs_to :away_team, class_name: 'Team'

  validates :home_team, presence: true
  validates :away_team, presence: true
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.all
    @team = current_user.team
  end

  def new
    @match = Match.new
    @team = current_user.team
  end

  def create
    user_team = Team.find(params[:match][:user_team_id])
    opponent_team = Team.find(params[:match][:opponent_team_id])

    @match = Match.new
    if params[:match][:home_or_away_team] == 'home_team'
      @match.home_team = user_team
      @match.away_team = opponent_team
    else
      @match.home_team = opponent_team
      @match.away_team = user_team
    end

    if @match.save
      redirect_to start_match_path(@match), notice: 'Partida criada com sucesso.'
    else
      render :new
    end
  end

  def show
    @match = Match.find(params[:id])
  end

  def start_match
    @match = Match.find(params[:id])
  end

  def generate_result
    @match = Match.find(params[:id])

    home_top_players = @match.home_team.players.where(injury: false).order(level: :desc).limit(11)
    away_top_players = @match.away_team.players.where(injury: false).order(level: :desc).limit(11)

    case home_top_players.sum(:level)
    when 0..353
      @match.home_score = rand(0..1)
    when 353..370
      @match.home_score = rand(0..2)
    when 371..465
      @match.home_score = rand(0..3)
    else
      @match.home_score = rand(0..4)
    end

    case away_top_players.sum(:level)
    when 0..353
      @match.away_score = rand(0..1)
    when 353..370
      @match.away_score = rand(0..2)
    when 371..465
      @match.away_score = rand(0..3)
    else
      @match.away_score = rand(0..4)
    end   

    if @match.save
      redirect_to match_path(@match)
    else
      flash[:alert] = 'Erro ao salvar o resultado.'
      render :show, status: :unprocessable_entity
    end
  end

  private

  def match_params
    params.require(:match).permit(:home_or_away_team, :opponent_team_id, :user_team_id)
  end
end

app/views/matches/index.html.erb
<div class="matches-index">
	<div class='container-matches-index'>
		<h1 class='text-center'>Suas partidas</h1>
    <div class="scrollable">
    <table>
      <thead class='text-center sticky-header'>
        <tr>
          <th class="col-home">Casa</th>
          <th class="col-home-score"></th>
          <th class="col-vs"></th>
          <th class="col-away-score"></th>
          <th class="col-away">Visitante</th>
        </tr>
      </thead>
      <tbody class='text-center'>
        <% @matches.select { |match| match.home_team == current_user.team || match.away_team == current_user.team }.reverse_each do |match| %>
          <tr>
            <td class="col-home"><%= match.home_team.name %></td>
            <td class="col-home-score"><%= match.home_score %></td>
            <td class="col-vs">X</td>
            <td class="col-away-score"><%= match.away_score %></td>
            <td class="col-away"><%= match.away_team.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
		</table>
		<%= image_tag 'match-new.jpeg', class: 'new-team' %>
	</div>
	<div class="matches-index-buttons">
	<%= link_to 'Voltar ao Time', team_path(@team), class: 'btn btn-secondary' %>
	<%= link_to 'Nova Partida', new_match_path, class: 'btn btn-primary' %>
	</div>
</div>

app/views/matches/new.html.erb
<div class="create-match">
<%= form_with(model: @match, url: matches_path, local: true) do |form| %>
  <div class="field">
    <%= form.label :home_or_away_team, "Quer ser o time da casa ou visitante?" %>
    <%= form.select :home_or_away_team, options_for_select([['Casa', 'home_team'], ['Visitante', 'away_team']]), {}, { class: 'rounded-select' } %>
  </div>

  <div class="field">
    <%= form.label :opponent_team, "Escolha o time adversário:" %>
    <%= form.collection_select :opponent_team_id, Team.where(user_id: nil), :id, :name, {}, { class: 'rounded-select' } %>
  </div>

  <% if current_user.team %>
  <%= form.hidden_field :user_team_id, value: current_user.team.id %>
  <% else %>
    <p>Você não tem um time associado. Por favor, associe um time antes de continuar.</p>
  <% end %>

  <div class="actions">
    <%= link_to 'Voltar', team_path(@team), class: 'btn btn-secondary' %>
    <%= form.submit "Criar Partida", class: "btn btn-primary" %>  
  </div>  
<% end %>
</div>

<%= image_tag 'match-new.jpeg', class: 'new-team' %>

app/views/matches/show.html.erb
<div class="matches-show-container">
  <div class="home-team text-center">
    <h2>Time da casa</h2>
    <%= @match.home_team.name %>
    <h3>Jogadores:</h3>
    <div class="scrollable">
      <table class="table table-striped">
        <thead class="fixed-header">
          <tr>
            <th class="th-name">Name</th>
            <th class="th-position">P</th>
            <th class="th-level">Level</th>
            <th class="th-yellow-card"><%= image_tag 'yellow_card.png', class: 'yellow-card-icon' %></th>
            <th class="th-red-card"><%= image_tag 'red_card.png', class: 'red-card-icon' %></th>  
            <th class="th-goal-ball"><%= image_tag 'goal_ball.png', class: 'goal-ball-icon' %></th>
            <th class="th-injury"><%= image_tag 'cruz-vermelha.png', class: 'injury-icon' %></th>
          </tr>
        </thead>
        <tbody>
          <% @match.home_team.players.sort_by { |player| ["G", "D", "M", "A"].index(player.position) || 4 }.each do |player| %>
            <tr>
              <td><%= player.name %></td>
              <td><%= player.position %></td>
              <td><%= player.level %></td>
              <td><%= player.yellow_card %></td>
              <td><%= player.red_card %></td>
              <td><%= player.goal_scored %></td>
              <td><% if player.injury %>
                    <%= image_tag 'cruz-vermelha.png', class: 'injury-icon' %>
                    <% else %>
                    <%= image_tag 'cruz-verde.png', class: 'health-icon' %>
                  <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>  
      </table>
    </div>
  </div>
  <div class="score text-center">
    <div id="score-content">
      <h2>Placar</h2>
      <div id="score-display"> <span id="home-score">0</span> - <span id="away-score">0</span> </div>
    </div>
    <div class="timer text-center" id="timer">00:00</div>
    <div>
      <%= link_to 'Suas Partidas', matches_path, class: 'btn btn-primary match-show-back-button', id: 'history-button', style: 'display: none;' %>
    </div>
  </div>
  <div class="away-team text-center">
    <h2>Visitante</h2>
    <%= @match.away_team.name %>
    <h3>Jogadores:</h3>
    <div class="scrollable">
      <table class="table table-striped">
        <thead class="fixed-header">
          <tr>
            <th class="th-name">Name</th>
            <th class="th-position">P</th>
            <th class="th-level">Level</th>
            <th class="th-yellow-card"><%= image_tag 'yellow_card.png', class: 'yellow-card-icon' %></th>
            <th class="th-red-card"><%= image_tag 'red_card.png', class: 'red-card-icon' %></th>  
            <th class="th-goal-ball"><%= image_tag 'goal_ball.png', class: 'goal-ball-icon' %></th>
            <th class="th-injury"><%= image_tag 'cruz-vermelha.png', class: 'injury-icon' %></th>
          </tr>
        </thead>
        <tbody>
          <% @match.away_team.players.sort_by { |player| ["G", "D", "M", "A"].index(player.position) || 4 }.each do |player| %>
            <tr>
              <td><%= player.name %></td>
              <td><%= player.position %></td>
              <td><%= player.level %></td>
              <td><%= player.yellow_card %></td>
              <td><%= player.red_card %></td>
              <td><%= player.goal_scored %></td>
              <td><% if player.injury %>
                    <%= image_tag 'cruz-vermelha.png', class: 'injury-icon' %>
                    <% else %>
                    <%= image_tag 'cruz-verde.png', class: 'health-icon' %>
                  <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>  
      </table>
    </div>
  </div>
</div>

<%= image_tag 'match-new.jpeg', class: 'new-team' %>

<script>
  var homeScore = <%= @match.home_score || 0 %>;
  var awayScore = <%= @match.away_score || 0 %>;

  document.addEventListener('DOMContentLoaded', function() {
    startTimer();
  });

  function generateRandomTimes(score) {
    const randomTimes = [];
    for (let i = 0; i < score; i++) {
      randomTimes.push((Math.floor(Math.random() * 540) + 1) * 10);
    }
    return randomTimes;  }


  function startTimer() {
    var timerElement = document.getElementById('timer');
    var historyButton = document.getElementById('history-button');
    var homeScoreElement = document.getElementById('home-score');
    var awayScoreElement = document.getElementById('away-score');
    var timeElapsed = 0;
    var totalTime = 90.5 * 60;
    timerElement.style.display = 'block';

    const homeGoalTimes = generateRandomTimes(homeScore);
    const awayGoalTimes = generateRandomTimes(awayScore);

    var countdown = setInterval(function() {
      if (timeElapsed >= totalTime) {
        clearInterval(countdown);
        historyButton.style.display = 'block';
      } else {
        var minutes = Math.floor(timeElapsed / 60);
        var seconds = timeElapsed % 60;
        timerElement.innerHTML = minutes + ":" + (seconds < 10 ? "0" : "") + seconds;
        timeElapsed += 1;
      }
      for (let i = 0; i < homeGoalTimes.length; i++) {
        if (timeElapsed == homeGoalTimes[i]) {
          alert('Gol do time da casa!');
          homeScoreElement.innerHTML = parseInt(homeScoreElement.innerHTML) + 1;
          break;
        }
      }
      for (let i = 0; i < awayGoalTimes.length; i++) {
        if (timeElapsed == awayGoalTimes[i]) {
          alert('Gol do time visitante!');
          awayScoreElement.innerHTML = parseInt(awayScoreElement.innerHTML) + 1;
          break;
        }
      }

      if (timeElapsed == 2750) {
        alert('Fim do primeiro tempo!');
      }
    }, 1);
  }
</script>

app/views/matches/start_match.html.erb
<div class="matches-start-match-container">
  <div class="home-team text-center">
    <h2>Time da casa</h2>
    <%= @match.home_team.name %>
    <h3>Jogadores:</h3>
    <div class="scrollable">
      <table class="table table-striped">
        <thead class="fixed-header">
          <tr>
            <th class="name-column">Name</th>
            <th class="position-column">P</th>
            <th class="level-column">Level</th>
            <th class="yellow-card-column"><%= image_tag 'yellow_card.png', class: 'yellow-card-icon' %></th>
            <th class="red-card-column"><%= image_tag 'red_card.png', class: 'red-card-icon' %></th>  
            <th class="goal-column"><%= image_tag 'goal_ball.png', class: 'goal-ball-icon' %></th>
            <th class="injury-column"><%= image_tag 'cruz-vermelha.png', class: 'injury-icon' %></th>
          </tr>
        </thead>
        <tbody>
          <% @match.home_team.players.sort_by { |player| ["G", "D", "M", "A"].index(player.position) || 4 }.each do |player| %>
            <tr>
              <td class="name-column"><%= player.name %></td>
              <td class="position-column"><%= player.position %></td>
              <td class="level-column"><%= player.level %></td>
              <td class="yellow-card-column"><%= player.yellow_card %></td>
              <td class="red-card-column"><%= player.red_card %></td>
              <td class="goal-column"><%= player.goal_scored %></td>
              <td class="injury-column">
                <% if player.injury %>
                  <%= image_tag 'cruz-vermelha.png', class: 'injury-icon' %>
                <% else %>
                  <%= image_tag 'cruz-verde.png', class: 'health-icon' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>  
      </table>
    </div>
  </div>
  <div class="score text-center">
    <%= form_with url: generate_result_match_path(@match), method: :post, id: 'start-match-form' do %>
      <%= submit_tag 'Iniciar Partida', class: "btn btn-primary", onclick: "startTimer(event)" %>
    <% end %>
    <div class="timer text-center" id="timer" style="display: none;">00:00</div>
  </div>
  <div class="away-team text-center">
    <h2>Visitante</h2>
    <%= @match.away_team.name %>
    <h3>Jogadores:</h3>
    <div class="scrollable">
      <table class="table table-striped">
        <thead class="fixed-header">
          <tr>
            <th class="name-column">Name</th>
            <th class="position-column">P</th>
            <th class="level-column">Level</th>
            <th class="yellow-card-column"><%= image_tag 'yellow_card.png', class: 'yellow-card-icon' %></th>
            <th class="red-card-column"><%= image_tag 'red_card.png', class: 'red-card-icon' %></th>  
            <th class="goal-column"><%= image_tag 'goal_ball.png', class: 'goal-ball-icon' %></th>
            <th class="injury-column"><%= image_tag 'cruz-vermelha.png', class: 'injury-icon' %></th>
          </tr>
        </thead>
        <tbody>
          <% @match.away_team.players.sort_by { |player| ["G", "D", "M", "A"].index(player.position) || 4 }.each do |player| %>
            <tr>
              <td class="name-column"><%= player.name %></td>
              <td class="position-column"><%= player.position %></td>
              <td class="level-column"><%= player.level %></td>
              <td class="yellow-card-column"><%= player.yellow_card %></td>
              <td class="red-card-column"><%= player.red_card %></td>
              <td class="goal-column"><%= player.goal_scored %></td>
              <td class="injury-column">
                <% if player.injury %>
                  <%= image_tag 'cruz-vermelha.png', class: 'injury-icon' %>
                <% else %>
                  <%= image_tag 'cruz-verde.png', class: 'health-icon' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>  
      </table>
    </div>
  </div>
</div>

<%= image_tag 'match-new.jpeg', class: 'new-team' %>

<script>
  function startTimer(event) {
    event.preventDefault();
    var timerElement = document.getElementById('timer');
    var timeElapsed = 0;
    var totalTime = 10;

    var countdown = setInterval(function() {
      if (timeElapsed >= totalTime) {
        clearInterval(countdown);
        document.getElementById('start-match-form').submit();
      } else {
        var minutes = Math.floor(timeElapsed / 60);
        var seconds = timeElapsed % 60;
        timerElement.innerHTML = minutes + ":" + (seconds < 10 ? "0" : "") + seconds;
        timeElapsed += 10;
      }
    }, 1);
  }
</script>